image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run webdriver-update
          - npm run pretest
          - npm run headlessTest